---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: minimal niri on ublue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    direct-pull: true

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - solopasha/hyprland
        # - lihaohong/yazi
      nonfree: rpmfusion

    install:
      skip-unavailable: true
      allow-erasing: true
      exclude:
        - alacritty
      packages:
        - adwaita-sans-fonts
        - android-tools
        - brightnessctl
      #  - code
        # - desktop-backgrounds-compat # Wallpapers
        - desktop-backgrounds-basic
        - btop
        - bazaar # present in ublue copr
        - curl
        - distrobox
        # - docker-ce
        # - docker-ce-cli
        - containerd.io
        - podman
        - fd-find
        - firewall-config
        - fuse-overlayfs # appimage support
        - fuzzel
        - fastfetch
        - git
        - gnome-keyring
        # - gnome-disk-utility
        - grim
        - gvfs
        - gvfs-mtp
        - gvfs-fuse
        - gvfs-archive
        - gvfs-nfs
        - gvfs-smb
        - hyprlock
        - kde-connect # nice to have
        - kitty
        #        - lightdm
        - mako
        - man-db
        - neovim
        - nautilus
        - network-manager-applet
        - blueman
        - niri
        # - nwg-wrapper
        - papirus-icon-theme
        #- python3-pip
        # - neovim
        - pavucontrol
        - playerctl
        - polkit
        - lxqt-policykit
        - powertop
        - ptyxis
        - papirus-icon-theme
        #- python3-pip
        - qt6ct
        - qt6-qtwayland
        - ripgrep
        - rofi
        - rofimoji
        - rustup
        - slurp
        # - slick-greeter
        - sddm
        # - sddm-breeze
        - sshfs
        - ssh
        - stow
        - swaybg
        - swayidle
        #- swaylock
        - tealdeer
        - toolbox
        - tuned-ppd
        - upower
        - uupd
        - waybar
        - wget
        - wf-recorder
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - zoxide
        - zsh
        - wlsunset
        - zstd
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - breeze-icon-theme
        - nvtop

  - type: systemd
    system:
      enabled:
        - podman.socket
        # - lightdm.service
        - sddm.service
        - uupd.timer
        # - docker.socket
    user:
      enabled:
        - waybar.service
        - gnome-keyring-daemon.socket
        - swaybg.service
        - swayidle.service
        - mako.service
        - lxqt-policykit.service

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: gschema-overrides
    include:
      - zz-ublue-niri.gschema.override

  # - type: script
  #   scripts:
  #     - post_build.sh

  - type: signing
