---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: minimal niri on ublue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
 
  - type: bling
    install:
      - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed
 
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
  
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - solopasha/hyprland
       # - lihaohong/yazi
      nonfree: rpmfusion


    install:
      skip-unavailable: true
      allow-erasing: true
      exclude:
        - alacritty
      packages:
        - adwaita-sans-fonts
        - android-tools
        - brightnessctl
        # - desktop-backgrounds-compat # Wallpapers
        - desktop-backgrounds-basic
        - btop
        - curl
        - distrobox
        - fd-find
        - firewall-config
        - fuse-overlayfs # appimage support
        - fuzzel
        - fastfetchW
        - git
        - gnome-keyring
        # - gnome-disk-utility
        - grim
        - gvfs
        - gvfs-mtp
        - gvfs-fuse
        - gvfs-archive
        - gvfs-nfs
        - gvfs-smb
        - hyprlock
       # - kde-connect # nice to have
        # - kitty
        - foot
        - mako
        - man-db
        - nautilus
        # - network-manager-applet
        - niri
        # - nwg-wrapper
       # - neovim
        - pavucontrol
        - playerctl
        - polkit
        - lxqt-policykit
        - powertop
        - ptyxis
       # - papirus-icon-theme
        #- python3-pip
        # - qt6ct
        # - qt6-qtwayland
        # - rclone
        - ripgrep
        - rofi
        - rofimoji
        - rustup
        - sddm
        - slurp
        #- sshfs
        - stow
        - swaybg
        - swayidle
        #- swaylock
        - toolbox
        # - tuned-ppd
        - upower
        - uupd
        - waybar
        - wget
        - wf-recorder
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - zoxide
        - zsh

    remove:
      packages:
        - firefox
        - firefox-langpacks 
        - breeze-icon-theme
        - nvtop
        - google-noto-sans-cjk-fonts
      
  - type: systemd
    system:
      enabled:
        - podman.socket
        - sddm.service
    user:
      enabled:
        - waybar.service
        - gnome-keyring-daemon.socket
        - swaybg.service
        - swayidle.service
        - mako.service
        - lxqt-policykit.service

  - type: fonts
    fonts:
      nerd-fonts:
        # - JetBrainsMono
        - NerdFontsSymbolsOnly
  - type: gschema-overrides
    include:
      - zz-ublue-niri.gschema.override

  - type: default-flatpaks
    configurations:
      - notify: true 
      - scope: user 
        install:
          - com.github.tchx84.Flatseal
          - io.github.kolunmi.Bazaar 
          - io.github.dvlv.boxbuddyrs
        
  # - type: script
  #   snippets:
  #     - "brew install yazi"

  - type: yafti
    custom-flatpaks:
      - Zen-Browser: app.zen_browser.zen
      - clipboard-manager: com.github.hluk.copyq
      - tauon-music-player: com.github.taiko2k.tauon-music-player
      - pavucontrol: org.pulseaudio.pavucontrol
      

  - type: signing 
