---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: minimal niri on ublue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    direct-pull: true

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: gschema-overrides
    include:
      - zz-ublue-niri.gschema.override

  # - type: script
  #   snippets:
  #     - "brew tap ublue-os/tap"
  #     - "brew install Valkyrie00/homebrew-bbrew/bbrew"
          
  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - solopasha/hyprland
        - bieszczaders/kernel-cachyos-addons
        - monkeygold/nautilus-open-any-terminal

        # annanicy rules and cachykernel
      nonfree: rpmfusion

    install:
      skip-unavailable: true
      allow-erasing: true
      exclude:
        - alacritty
      packages:
        - adwaita-sans-fonts
        - android-tools
        - ananicy-cpp
        - cachyos-ananicy-rules
        - brightnessctl
        - desktop-backgrounds-basic
        - flatpak-builder
        - btop
        - bazaar
        - curl
        - cava
        - copyq
        - distrobox
        # - docker-ce
        # - docker-ce-cli
        - containerd.io
        - podman
        - fd-find
        - fzf
        - firewall-config
        - fuse-overlayfs # appimage support
        - fuzzel
        - fastfetch
        - git
        - gnome-keyring
        - grim
        - gvfs
        - gvfs-mtp
        - gvfs-fuse
        - gvfs-archive
        - gvfs-nfs
        - gvfs-smb
        - hyprlock
        - kde-connect # nice to have
        - kitty
        #- lightdm
        - mako
        - man-db
        - neovim
        - nautilus
        - blueman-nautilus
        - kde-connect-nautilus
        - nautilus-python
        - nautilus-open-any-terminal
        - sushi
        - network-manager-applet
        - NetworkManager-openvpn
        - blueman
        - niri
        - nwg-wrapper
        - papirus-icon-theme
        - python3-neovim
        - pavucontrol
        - playerctl
        - polkit
        - mate-polkit
        - powertop
        - podman-compose
        - ptyxis
        - python-pip
        - qt6ct
        - qt6-qtwayland
        - ripgrep
        - rofi
        - rofimoji
        - rustup
        - slurp
        - sddm
        - sshfs
        - ssh
        - stow
        - swaybg
        - swayidle
        #- swaylock
        - tldr
        - toolbox
        - upower
        - uupd
        - waybar
        - wget
        - wf-recorder
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - zoxide
        - zsh
        - wlsunset
        - zstd

    remove:
      auto-remove: true
      packages:
        - weston
        - firefox
        - firefox-langpacks
        - breeze-icon-theme
        - nvtop
        - htop
     
  - type: systemd
    system:
      enabled:
        - podman.socket
        # - lightdm.service
        - sddm.service
        - ananicy-cpp.service
        - uupd.timer
        # - docker.socket
    user:
      enabled:
        - waybar.service
        - gnome-keyring-daemon.socket
        - swaybg.service
        - swayidle.service
        - mako.service
        - wlsunset
        - polkit-mate.service

  - type: signing
