---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ublue-niri
base-image: ghcr.io/ublue-os/base-main
description: Atomic distro with the Niri and noctalia shell
image-version: latest 

modules:
  - type: files
    files:
      - source: system
        destination: / 
  
  - type: brew
    nofile-limits: true
    brew-analytics: false
    direct-pull: true

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: gschema-overrides
    include:
      - zz-ublue-niri.gschema.override

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - bieszczaders/kernel-cachyos-addons
      nonfree: rpmfusion
    install:
      allow-erasing: true
      exclude:
        - alacritty
        - waybar
        - mako
      packages:
        - adw-gtk3-theme
        - cachyos-ananicy-rules
        - bazaar
        - btop
        - bluez-tools
        - distrobox
        - podman
        - fd-find
        - fzf
        - firewall-config
        - fuse-overlayfs
        - fprintd
        - fprintd-pam
        - fastfetch
        - git
        - gnome-keyring
        - gvfs
        - gvfs-mtp
        - gvfs-fuse
        - gvfs-archive
        - gvfs-nfs
        - gvfs-smb
        - kitty
        - nautilus
        - blueman-nautilus
        - noctalia-shell
        - lightdm-gtk
        - nautilus-python
        - NetworkManager-openvpn
        - niri
        - papirus-icon-theme
        # - nwg-look
        - polkit
        - mate-polkit
        - podman-compose
        - qt6ct
        - qt6-qttools
        - qt6-qtwayland
        - tldr
        - tuned-ppd
        - toolbox
        - upower
        - uupd
        - uwsm
        - wtype
        - wl-mirror
        - wireguard-tools
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - zoxide
        - zsh
        - zstd

    remove:
      auto-remove: true
      packages:
        - weston
        - firefox
        - firefox-langpacks
        - breeze-icon-theme
        - waybar
        - nvtop
        - htop
        - mako

  - type: systemd
    system:
      enabled:
        - podman.socket
        - lightdm.service
        - uupd.timer

    user:
      enabled:
        - gnome-keyring-daemon.socket
        - polkit-mate.service
      disabled:
        - waybar.service
        - mako.service

  - type: os-release
    properties:
      ID: Kanso
      NAME: Kanso Linux
      PRETTY_NAME: Kanso Linux
      ID_LIKE: fedora
      DEFAULT_HOSTNAME: kanso-linux
  
  # - type: custom-kernel
  #   kernel: cachyos
  #   initramfs: true

  - type: initramfs
  - type: signing
