---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: minimal niri on ublue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
 
  - type: bling
    install:
      - rpmfusion # install RPMFusion repos, including tainted repos & disable negativo17 repos if installed
 
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
  
  - type: dnf
    repos:
      cleanup: true
      copr:
        - erikreider/swayosd
      nonfree: rpmfusion


    install:
      skip-unavailable: true
      allow-erasing: true
      exclude:
        - alacritty
      packages:
        - android-tools
        - btop
        - code
        - copyq
        - curl
        - fd-find
        - firewall-config
        - fuse-overlayfs # appimage support
        - fuzzel
        - gcc
        - git
        - gnome-keyring
        - grim
        - gvfs
        - gvfs-mtp
        - gvfs-nfs
        - gvfs-smb
        - imv
        - kde-connect # nice to have
        - kitty
        - mako
        - make
        - man-db
        - nautilus
        - neovim
        - network-manager-applet
        - niri
        - nwg-wrapper
        - p7zip
        - p7zip-plugins
        - pavucontrol
        - playerctl
        - polkit
        - polkit-gnome 
        - polkit-kde
        - powertop
        - ptyxis
        - python3-pip
        - qt6ct
        - qt6-qtwayland
        - rclone
        - ripgrep
        - rofi
        - rofimoji
        - rustup
        - sddm
        - slurp
        - sshfs
        - stow
        - swaybg
        - swayidle
        - swaylock
        - swayosd
        - tailscale
        - tealdeer
        - toolbox
        - tuned-ppd
        - upower
        - waybar
        - wget
        - wf-recorder
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - zoxide
        - zsh
         

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)List of custom Flatpaks to inject to the default yafti.yml. Format is: PrettyName: org.example.flatpak_id
  

      
  - type: systemd
  # this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - swayosd-libinput-backend.service
        - podman.socket
        - sddm.service
    user:
      enabled:
        - waybar.service
        - gnome-keyring-daemon.socket
        # - gnome-polkit.service
        - swaybg.service
        - swayidle.service
        - mako.service
        - copyq.service
        - plasma-polkit-agent.service

  - type: fonts
    fonts:
      nerd-fonts:
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        #install: # system flatpaks we want all users to have and not remove

      - scope: user # Also add Flathub user repo, but no user packages
        install:
          - com.github.tchx84.Flatseal
          - io.github.kolunmi.Bazaar    
        
  - type: script
    snippets:
      - "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'"
      - "dconf write /org/gnome/desktop/interface/color-scheme '\"prefer-dark\"'"
      - "gsettings set org.gnome.desktop.wm.preferences button-layout :" # example: ld alternatives symlink workaround
  - type: yafti
    custom-flatpaks:
      - VLC: org.videolan.VLC
      - Zen-Browser: app.zen_browser.zen
      

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
