---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: minimal niri on ublue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
    direct-pull: true

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: gschema-overrides
    include:
      - zz-ublue-niri.gschema.override

  - type: dnf
    repos:
      cleanup: true
      copr:
        - ublue-os/packages
        - solopasha/hyprland
        - bieszczaders/kernel-cachyos-addons
        - avengemedia/dms
      nonfree: rpmfusion

    install:
      skip-unavailable: true
      allow-erasing: true
      exclude:
        - alacritty
      packages:
        - android-tools
        - ananicy-cpp
        - cachyos-ananicy-rules
        - brightnessctl
        - btop
        - bazaar
        - curl
        - cava
        - containerd.io
        - distrobox
        - podman
        - fd-find
        - fzf
        - firewall-config
        - fuse-overlayfs # appimage support
        - fuzzel
        - fastfetch
        - git
        - gnome-keyring
        - gvfs
        - gvfs-mtp
        - gvfs-fuse
        - gvfs-archive
        - gvfs-nfs
        - gvfs-smb
        - kde-connect # nice to have
        - kitty
        - man-db
        - neovim
        - nautilus
        - blueman-nautilus
        - kde-connect-nautilus
        - dms
        - dms-greeter
        - nautilus-python
        - sushi
        - NetworkManager-openvpn
        - NetworkManager-tui
        - niri
        - papirus-icon-theme
        - python3-neovim
        - pavucontrol
        - playerctl
        - polkit
        - mate-polkit
        - podman-compose
        - qt6-qtwayland
        - ripgrep
        - rofi
        - rofimoji
        - sshfs
        - ssh
        - tldr
        - tuned-ppd
        - toolbox
        - upower
        - uupd
        - uwsm
        - wget
        - xdg-desktop-portal-gnome
        - xdg-desktop-portal-gtk
        - xwayland-satellite
        - zoxide
        - zsh
        - wlsunset
        - zstd

    remove:
      auto-remove: true
      packages:
        - weston
        - firefox
        - firefox-langpacks
        - breeze-icon-theme
        - nvtop
        - htop

  - type: systemd
    system:
      enabled:
        - podman.socket
        - greetd.service
        - ananicy-cpp.service
        - uupd.timer

    user:
      enabled:
        - dms
        - gnome-keyring-daemon.socket
        - polkit-mate.service
      disabled:
        - mako.service

  - type: signing
