confirm_os_window_close 0
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 1

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16

mouse_map right release ungrabbed paste_from_clipboard

# Enable notifications
detect_urls yes
copy_on_select yes
enable_audio_bell no

map ctrl+alt+left  neighboring_window left
map ctrl+alt+right neighboring_window right
map ctrl+alt+up    neighboring_window top
map ctrl+alt+down  neighboring_window bottom
map ctrl+shift+[   previous_tab
map ctrl+shift+]   next_tab
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map shift+insert paste_from_selection

shell /usr/bin/zsh
